import { createHash } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";

const domain = JSON.parse(readFileSync("assets/rag/domain_terms.v1.json", "utf8"));
const exercise = JSON.parse(readFileSync("assets/rag/exercise_terms.v1.json", "utf8"));
const exercisePayload = JSON.stringify(exercise.exercises);
const exercises = exercise.exercises.map((definition) => ({
  ...definition,
  definition_hash: createHash("sha256").update(JSON.stringify(definition)).digest("hex"),
}));
const snapshot = {
  schema_version: "fitlog_exercise_catalog_snapshot.v1",
  catalog_version: exercise.catalog_version,
  catalog_hash: createHash("sha256").update(exercisePayload).digest("hex"),
  exercise_count: exercise.exercises.length,
  exercises,
};
const output = `// Generated by tool/rag_foundation/export_edge_rag_assets.mjs.\n` +
  `export const domainTerms = ${JSON.stringify(domain, null, 2)} as const;\n\n` +
  `export const exerciseCatalogSnapshot = ${JSON.stringify(snapshot, null, 2)} as const;\n`;
writeFileSync("supabase/functions/ai-chat-route/generated/rag_assets.v1.ts", output, "utf8");
const dartHashes = `// Generated by tool/rag_foundation/export_edge_rag_assets.mjs.\n` +
  `const Map<String, String> exerciseDefinitionHashes = <String, String>${JSON.stringify(Object.fromEntries(exercises.map((item) => [item.key, item.definition_hash])), null, 2).replaceAll('"', "'")};\n`;
writeFileSync("lib/core/constants/generated/exercise_definition_hashes.dart", dartHashes, "utf8");
console.log(`Exported ${domain.concepts.length} concepts and ${exercise.exercises.length} exercises (${snapshot.catalog_hash}).`);
