import { createHash } from "node:crypto";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

const repoRoot = process.cwd();
const generatorVersion = "phase5_document_chunks.v3";
const maxChunkLength = 1400;
const sourcePaths = [
  "README.md",
  "docs/en/Product.md",
  "docs/en/AppGuide.md",
  "docs/en/Methodology.md",
  "docs/en/Algorithm.md",
  "docs/en/Database.md",
  "docs/en/AgentDesign.md",
  "docs/en/AIOutputContract.md",
  "docs/en/RAGDesign.md",
  "docs/en/References.md",
  "docs/zh/Product.md",
  "docs/zh/AppGuide.md",
  "docs/zh/Methodology.md",
  "docs/zh/Algorithm.md",
  "docs/zh/Database.md",
  "docs/zh/AgentDesign.md",
  "docs/zh/AIOutputContract.md",
  "docs/zh/RAGDesign.md",
  "docs/zh/References.md",
];

const chunks = [];
for (const relativePath of sourcePaths) {
  const absolutePath = path.join(repoRoot, relativePath);
  if (!existsSync(absolutePath)) {
    continue;
  }
  chunks.push(...chunksForFile(relativePath, readFileSync(absolutePath, "utf8")));
}

const lines = [
  "-- Generated by tool/phase5_document_rag/build_document_chunks.mjs",
  "-- Re-run after stable design docs change, then apply after the Phase 5 migration.",
  "begin;",
  "delete from public.document_chunks",
  `where doc_path = any (${sqlTextArray(sourcePaths)});`,
  "",
  "insert into public.document_chunks (language, doc_path, heading, heading_level, heading_path, section_id, chunk_index, chunk_count, content, context_prefix, context_note, tags, status, content_hash, generator_version, source_updated_at)",
  "values",
  chunks.map(sqlTuple).join(",\n"),
  "on conflict (language, doc_path, section_id) do update set",
  "  heading = excluded.heading,",
  "  heading_level = excluded.heading_level,",
  "  heading_path = excluded.heading_path,",
  "  chunk_index = excluded.chunk_index,",
  "  chunk_count = excluded.chunk_count,",
  "  content = excluded.content,",
  "  context_prefix = excluded.context_prefix,",
  "  context_note = excluded.context_note,",
  "  tags = excluded.tags,",
  "  status = excluded.status,",
  "  content_hash = excluded.content_hash,",
  "  generator_version = excluded.generator_version,",
  "  source_updated_at = excluded.source_updated_at,",
  "  updated_at = timezone('utc', now())",
  "where public.document_chunks.content_hash is distinct from excluded.content_hash",
  "   or public.document_chunks.heading is distinct from excluded.heading",
  "   or public.document_chunks.heading_level is distinct from excluded.heading_level",
  "   or public.document_chunks.heading_path is distinct from excluded.heading_path",
  "   or public.document_chunks.chunk_index is distinct from excluded.chunk_index",
  "   or public.document_chunks.chunk_count is distinct from excluded.chunk_count",
  "   or public.document_chunks.context_prefix is distinct from excluded.context_prefix",
  "   or public.document_chunks.context_note is distinct from excluded.context_note",
  "   or public.document_chunks.tags is distinct from excluded.tags",
  "   or public.document_chunks.status is distinct from excluded.status",
  "   or public.document_chunks.generator_version is distinct from excluded.generator_version;",
  "commit;",
  "",
];

writeFileSync(
  path.join(repoRoot, "supabase", "seed_phase5_document_chunks.sql"),
  lines.join("\n"),
  "utf8",
);

console.log(`Wrote ${chunks.length} document chunks.`);

function chunksForFile(relativePath, markdown) {
  const normalizedPath = relativePath.replaceAll("\\", "/");
  const sections = parseMarkdownSections(normalizedPath, markdown);
  const result = [];

  for (let sectionIndex = 0; sectionIndex < sections.length; sectionIndex += 1) {
    const section = sections[sectionIndex];
    const normalized = normalizeContent(section.lines.join("\n"));
    if (normalized === "") {
      continue;
    }

    const language = languageFor(normalizedPath, section.headingPath, normalized);
    const tags = tagsFor(normalizedPath, section.headingPath, normalized);
    const status = statusFor(normalizedPath, section.headingPath, normalized);
    const split = recursiveSplit(normalized, maxChunkLength);

    for (let index = 0; index < split.length; index += 1) {
      const content = split[index].trim();
      if (content === "") {
        continue;
      }
      const chunkIndex = index + 1;
      const chunkCount = split.length;
      const contextPrefix = contextPrefixFor({
        language,
        docPath: normalizedPath,
        headingPath: section.headingPath,
        status,
        tags,
        chunkIndex,
        chunkCount,
      });
      const hashPayload = JSON.stringify({
        generatorVersion,
        headingPath: section.headingPath,
        status,
        tags,
        contextPrefix,
        content,
      });

      result.push({
        language,
        docPath: normalizedPath,
        heading: section.heading,
        headingLevel: section.level,
        headingPath: section.headingPath,
        sectionId: sectionIdFor(normalizedPath, section.headingPath, sectionIndex + 1, chunkIndex),
        chunkIndex,
        chunkCount,
        content,
        contextPrefix,
        contextNote: null,
        tags,
        status,
        contentHash: createHash("sha256").update(hashPayload).digest("hex"),
        generatorVersion,
      });
    }
  }
  return result;
}

function parseMarkdownSections(relativePath, markdown) {
  const sections = [];
  const defaultHeading = path.basename(relativePath);
  const stack = [];
  let current = {
    heading: defaultHeading,
    level: 1,
    headingPath: [defaultHeading],
    lines: [],
  };

  for (const line of markdown.split(/\r?\n/)) {
    const match = /^(#{1,6})\s+(.+?)\s*$/.exec(line);
    if (match) {
      pushSection(sections, current);
      const level = match[1].length;
      const heading = stripMarkdown(match[2]);
      while (stack.length > 0 && stack[stack.length - 1].level >= level) {
        stack.pop();
      }
      stack.push({ level, heading });
      current = {
        heading,
        level,
        headingPath: stack.map((item) => item.heading),
        lines: [line],
      };
      continue;
    }
    current.lines.push(line);
  }
  pushSection(sections, current);
  return sections;
}

function pushSection(sections, section) {
  if (section.lines.join("").trim() !== "") {
    sections.push(section);
  }
}

function languageFor(relativePath, headingPath, content) {
  if (relativePath.startsWith("docs/zh/")) {
    return "zh";
  }
  if (relativePath.startsWith("docs/en/")) {
    return "en";
  }
  const pathText = headingPath.join(" ");
  if (/中文|Chinese/i.test(pathText) && !/English/i.test(pathText)) {
    return "zh";
  }
  if (/English|英文/i.test(pathText)) {
    return "en";
  }
  return cjkRatio(content) >= 0.15 ? "zh" : "en";
}

function cjkRatio(value) {
  const chars = [...value].filter((char) => !/\s/.test(char));
  if (chars.length === 0) {
    return 0;
  }
  const cjk = chars.filter((char) => {
    const code = char.codePointAt(0) ?? 0;
    return (code >= 0x4e00 && code <= 0x9fff) ||
      (code >= 0x3400 && code <= 0x4dbf);
  }).length;
  return cjk / chars.length;
}

function normalizeContent(value) {
  return value
    .replace(/\u0000/g, "")
    .replace(/[ \t]+\n/g, "\n")
    .replace(/\n{3,}/g, "\n\n")
    .trim();
}

function recursiveSplit(value, maxLength) {
  if (value.length <= maxLength) {
    return [value];
  }
  return splitByUnits(value, maxLength, /\n{2,}/, "\n\n").flatMap((paragraphGroup) => {
    if (paragraphGroup.length <= maxLength) {
      return [paragraphGroup];
    }
    return splitSentences(paragraphGroup, maxLength).flatMap((sentenceGroup) =>
      sentenceGroup.length <= maxLength ? [sentenceGroup] : hardSplit(sentenceGroup, maxLength)
    );
  });
}

function splitByUnits(value, maxLength, separator, joiner) {
  const units = value.split(separator).map((item) => item.trim()).filter((item) => item !== "");
  if (units.length === 0) {
    return [];
  }
  const result = [];
  let current = "";
  for (const unit of units) {
    const next = current === "" ? unit : `${current}${joiner}${unit}`;
    if (next.length > maxLength && current !== "") {
      result.push(current);
      current = unit;
    } else {
      current = next;
    }
  }
  if (current !== "") {
    result.push(current);
  }
  return result;
}

function splitSentences(value, maxLength) {
  const sentences = value
    .match(/[^。！？.!?；;\n]+[。！？.!?；;]?|\n+/g)
    ?.map((item) => item.trim())
    .filter((item) => item !== "") ?? [];
  if (sentences.length === 0) {
    return hardSplit(value, maxLength);
  }
  return splitByUnits(sentences.join("\n"), maxLength, /\n+/, " ");
}

function hardSplit(value, maxLength) {
  const result = [];
  for (let start = 0; start < value.length; start += maxLength) {
    result.push(value.slice(start, start + maxLength).trim());
  }
  return result.filter((item) => item !== "");
}

function contextPrefixFor({ language, docPath, headingPath, status, tags, chunkIndex, chunkCount }) {
  const location = `${docPath} > ${headingPath.join(" > ")}`;
  const part = chunkCount > 1 ? ` ${chunkIndex}/${chunkCount}` : "";
  if (language === "zh") {
    return `来源: ${location}${part}。状态: ${status}。标签: ${tags.join(", ")}。用途: 回答 FitLog 的产品规则、算法、数据库、隐私边界或 Agent 行为边界。`;
  }
  return `Source: ${location}${part}. Status: ${status}. Tags: ${tags.join(", ")}. Purpose: answer FitLog product-rule, algorithm, database, privacy-boundary, or Agent-boundary questions.`;
}

function stripMarkdown(value) {
  return value
    .replace(/[`*#[\]]/g, "")
    .replace(/\((.*?)\)/g, "$1")
    .trim();
}

function sectionIdFor(relativePath, headingPath, sectionIndex, chunkIndex) {
  const source = `${relativePath}:${headingPath.join(">")}:${sectionIndex}:${chunkIndex}`;
  return `${slug(headingPath.join("-"))}-${createHash("sha1").update(source).digest("hex").slice(0, 10)}`;
}

function slug(value) {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9\u4e00-\u9fff]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 72) || "section";
}

function tagsFor(relativePath, headingPath, content) {
  const source = `${relativePath}\n${headingPath.join(" ")}\n${content}`.toLowerCase();
  const tags = [];
  addTag(tags, "agent", source, ["agent", "ai", "llm", "rag", "gateway", "智能", "助手", "模型", "检索"]);
  addTag(tags, "database", source, ["database", "schema", "sqlite", "supabase", "migration", "rls", "数据库", "迁移"]);
  addTag(tags, "algorithm", source, ["algorithm", "energy_ratio", "gram_per_kg", "kcal", "macro", "算法", "热量", "宏量"]);
  addTag(tags, "methodology", source, ["methodology", "carb", "protein", "fat", "evidence", "方法", "碳水", "蛋白", "脂肪"]);
  addTag(tags, "privacy", source, ["privacy", "consent", "local", "cloud", "retention", "隐私", "本地", "云端", "留存"]);
  addTag(tags, "phase5", source, ["phase 5", "phase5", "阶段 5"]);
  addTag(tags, "ui", source, ["ui", "ux", "page", "screen", "tab", "界面", "页面", "入口"]);
  if (tags.length === 0) {
    tags.push("product");
  }
  return [...new Set(tags)];
}

function addTag(tags, tag, source, needles) {
  if (needles.some((needle) => source.includes(needle))) {
    tags.push(tag);
  }
}

function statusFor(relativePath, headingPath, content) {
  const heading = headingPath.join(" ").toLowerCase();
  const leadingContent = content
    .split(/\r?\n/)
    .map((line) => line.trim())
    .filter((line) => line !== "" && !line.startsWith("#"))
    .slice(0, 3)
    .join(" ")
    .toLowerCase();

  if (relativePath.endsWith("References.md")) {
    return "evidence";
  }
  if (
    heading.includes("non-goal") ||
    heading.includes("non_goal") ||
    heading.includes("out of scope") ||
    heading.includes("不做") ||
    heading.includes("非目标") ||
    /^(?:\*\*)?(?:non-goals?|out of scope|非目标|不做)\s*[:：]/.test(leadingContent)
  ) {
    return "non_goal";
  }
  if (
    heading.includes("planned") ||
    heading.includes("future") ||
    heading.includes("not implemented") ||
    heading.includes("计划范围") ||
    heading.includes("计划中") ||
    heading.includes("未来范围") ||
    heading.includes("尚未实现") ||
    /^(?:\*\*)?(?:planned(?: scope)?|future scope|not implemented|计划(?:范围)?|尚未实现)\s*[:：]/.test(
      leadingContent,
    )
  ) {
    return "planned";
  }
  if (
    heading.includes("local baseline") ||
    heading.includes("local version") ||
    heading.includes("local 版") ||
    heading.includes("本地版")
  ) {
    return "local_baseline";
  }
  return "implemented";
}

function sqlTuple(chunk) {
  return [
    "(",
    sqlString(chunk.language),
    ", ",
    sqlString(chunk.docPath),
    ", ",
    sqlString(chunk.heading),
    ", ",
    chunk.headingLevel,
    ", ",
    sqlTextArray(chunk.headingPath),
    ", ",
    sqlString(chunk.sectionId),
    ", ",
    chunk.chunkIndex,
    ", ",
    chunk.chunkCount,
    ", ",
    sqlString(chunk.content),
    ", ",
    sqlString(chunk.contextPrefix),
    ", ",
    chunk.contextNote === null ? "null" : sqlString(chunk.contextNote),
    ", ",
    sqlTextArray(chunk.tags),
    ", ",
    sqlString(chunk.status),
    ", ",
    sqlString(chunk.contentHash),
    ", ",
    sqlString(chunk.generatorVersion),
    ", timezone('utc', now()))",
  ].join("");
}

function sqlString(value) {
  return `'${String(value).replaceAll("'", "''")}'`;
}

function sqlTextArray(values) {
  if (values.length === 0) {
    return "'{}'::text[]";
  }
  return `array[${values.map(sqlString).join(", ")}]::text[]`;
}
