import { createHash } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

import { chunkMarkdown } from "./chunk_markdown.mjs";
import { loadAndValidateManifest } from "./validate_document_corpus.mjs";

const repoRoot = process.cwd();
const manifestPath = "tool/phase5_document_rag/document_corpus_manifest.v1.json";
const { manifest, manifestHash } = loadAndValidateManifest({ repoRoot, manifestPath });
const termVersion = manifest.term_versions.join("+");
const chunks = manifest.sources.flatMap((sourcePath) => chunkMarkdown({
  sourcePath,
  markdown: readFileSync(path.join(repoRoot, sourcePath), "utf8"),
  manifestHash,
  generatorVersion: manifest.generator_version,
  termVersion,
})).map((chunk) => ({
  ...chunk,
  searchTokens: segmentSearchText([
    chunk.heading,
    ...chunk.headingPath,
    chunk.content,
    chunk.contextPrefix,
    ...chunk.tags,
  ].join("\n")),
}));
const buildId = createHash("sha256")
  .update(JSON.stringify(chunks.map((chunk) => [
    chunk.sectionId,
    chunk.chunkHash,
    chunk.generatorVersion,
    chunk.termVersion,
    chunk.authority,
    chunk.searchTokens,
  ])))
  .digest("hex")
  .slice(0, 24);

const artifact = {
  schema: "fitlog_document_corpus_build.v1",
  corpus_id: manifest.corpus_id,
  build_id: buildId,
  manifest_hash: manifestHash,
  generator_version: manifest.generator_version,
  term_version: termVersion,
  source_count: manifest.sources.length,
  chunk_count: chunks.length,
  sources: manifest.sources,
  chunks,
};

writeFileSync(
  path.join(repoRoot, "tool", "phase5_document_rag", "document_corpus_build.v1.json"),
  `${JSON.stringify(artifact, null, 2)}\n`,
  "utf8",
);
writeFileSync(
  path.join(repoRoot, "supabase", "seed_phase5_document_chunks.sql"),
  renderSeed(artifact),
  "utf8",
);
console.log(`Wrote ${chunks.length} chunks from ${manifest.sources.length} sources for build ${buildId}.`);

export function renderSeed(build) {
  const lines = [
    "-- Generated by tool/phase5_document_rag/build_document_chunks.mjs",
    "-- Apply after 202607130001_rag_foundation_document_hybrid.sql.",
    "begin;",
    "select public.begin_document_corpus_build(",
    `  ${sqlString(build.corpus_id)}, ${sqlString(build.build_id)}, ${sqlString(build.manifest_hash)},`,
    `  ${sqlString(build.generator_version)}, ${sqlString(build.term_version)},`,
    `  ${build.source_count}, ${build.chunk_count}`,
    ");",
    "",
    "insert into public.document_chunks (corpus_id, build_id, language, doc_path, heading, heading_level, heading_path, section_id, chunk_index, chunk_count, content, context_prefix, context_note, tags, search_tokens, status, authority, source_hash, chunk_hash, content_hash, manifest_hash, generator_version, term_version, source_updated_at)",
    "values",
    build.chunks.map((chunk) => sqlTuple(build, chunk)).join(",\n"),
    "on conflict (corpus_id, build_id, language, doc_path, section_id) do update set",
    "  content = excluded.content, context_prefix = excluded.context_prefix, tags = excluded.tags, search_tokens = excluded.search_tokens,",
    "  status = excluded.status, source_hash = excluded.source_hash, chunk_hash = excluded.chunk_hash,",
    "  content_hash = excluded.content_hash, manifest_hash = excluded.manifest_hash,",
    "  generator_version = excluded.generator_version, term_version = excluded.term_version,",
    "  updated_at = timezone('utc', now());",
    "commit;",
    "",
  ];
  return lines.join("\n");
}

function sqlTuple(build, chunk) {
  return `(${[
    build.corpus_id,
    build.build_id,
    chunk.language,
    chunk.docPath,
    chunk.heading,
  ].map(sqlString).join(", ")}, ${chunk.headingLevel}, ${sqlTextArray(chunk.headingPath)}, ${sqlString(chunk.sectionId)}, ${chunk.chunkIndex}, ${chunk.chunkCount}, ${[
    chunk.content,
    chunk.contextPrefix,
  ].map(sqlString).join(", ")}, null, ${sqlTextArray(chunk.tags)}, ${sqlTextArray(chunk.searchTokens)}, ${[
    chunk.status,
    chunk.authority,
    chunk.sourceHash,
    chunk.chunkHash,
    chunk.contentHash,
    chunk.manifestHash,
    chunk.generatorVersion,
    chunk.termVersion,
  ].map(sqlString).join(", ")}, timezone('utc', now()))`;
}

function sqlString(value) {
  return `'${String(value).replaceAll("'", "''")}'`;
}

function sqlTextArray(values) {
  return `array[${values.map(sqlString).join(", ")}]::text[]`;
}

export function segmentSearchText(value) {
  const normalized = value.normalize("NFKC").toLowerCase().replace(/[\s\u3000]+/g, " ").trim();
  const tokens = normalized.match(/[a-z][a-z0-9_./-]*|\d+(?:\.\d+)?/gu) ?? [];
  const cjkRuns = normalized.match(/[\u3400-\u4dbf\u4e00-\u9fff]+/gu) ?? [];
  for (const run of cjkRuns) {
    const characters = [...run];
    if (characters.length <= 12) tokens.push(run);
    for (let size = 4; size >= 2; size -= 1) {
      for (let index = 0; index + size <= characters.length; index += 1) {
        tokens.push(characters.slice(index, index + size).join(""));
      }
    }
  }
  return [...new Set(tokens.filter((token) => token.length > 1))].slice(0, 256);
}
